syntax enable
set tabstop=4
set softtabstop=4
set expandtab
set number
set showcmd
filetype indent on
set showmatch

set incsearch
set hlsearch



"Start NERDTree on startup
"autocmd vimenter * NERDTree

"Start NT when no files specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

"Open NT when opening directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif

"Map NT
map <C-n> :NERDTreeToggle<CR>

"Close vim if only open window is NT
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
